// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3BpfuOlLZzncbKeeaqASNrrE0SQjQffE',
    appId: '1:823271589581:web:b479c6df168fee0ca24b84',
    messagingSenderId: '823271589581',
    projectId: 'epuskesmas-d55b0',
    authDomain: 'epuskesmas-d55b0.firebaseapp.com',
    databaseURL: 'https://epuskesmas-d55b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'epuskesmas-d55b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHqE15l78LFP5Ka2MzZpMCzVdsg4nC_VU',
    appId: '1:823271589581:android:a50f6e7d9be46bf4a24b84',
    messagingSenderId: '823271589581',
    projectId: 'epuskesmas-d55b0',
    databaseURL: 'https://epuskesmas-d55b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'epuskesmas-d55b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSlWUSASMAY1w_mgn3jyAtchy2fdaYGQs',
    appId: '1:823271589581:ios:63d7a52e2ecf23a4a24b84',
    messagingSenderId: '823271589581',
    projectId: 'epuskesmas-d55b0',
    databaseURL: 'https://epuskesmas-d55b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'epuskesmas-d55b0.appspot.com',
    androidClientId: '823271589581-3dmmhv4pttfk7lj0n2ishpscbtum9tcc.apps.googleusercontent.com',
    iosClientId: '823271589581-d2e53ktulj85b22nd67g1sgggub22hi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.epuskesmas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSlWUSASMAY1w_mgn3jyAtchy2fdaYGQs',
    appId: '1:823271589581:ios:63d7a52e2ecf23a4a24b84',
    messagingSenderId: '823271589581',
    projectId: 'epuskesmas-d55b0',
    databaseURL: 'https://epuskesmas-d55b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'epuskesmas-d55b0.appspot.com',
    androidClientId: '823271589581-3dmmhv4pttfk7lj0n2ishpscbtum9tcc.apps.googleusercontent.com',
    iosClientId: '823271589581-d2e53ktulj85b22nd67g1sgggub22hi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.epuskesmas',
  );
}
